package gateway

import (
	"context"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	// Absolute structural paths using your go.mod module name:
	queuev1 "forgequeue/proto/v1"
)

// server private struct having pointer to taskrouter to we can transfer downward to redis
// Implementing the service interface generated by the protobuf compiler
// Running a gRPC server to listen for requests from clients and dispatch them to the right service implementation.
type server struct {
	queuev1.UnimplementedQueueServiceServer
	trouter *TaskRouter
}

// task router knows what to do but soemthing to call this needed via rpc
// method belonging to the server struct acting as enquetas handler pushing data down the connection pool and generate uuid
// function must return 2 things a response pointer and an error as return response,error
func (s *server) EnqueueTask(
	ctx context.Context,
	req *queuev1.EnqueueTaskRequest,
) (*queuev1.EnqueueTaskResponse, error) {

	//gaurd clause: block empty task types
	if req.TaskType == "" {
		//no response and status error and grpc understands codes
		return nil, status.Error(codes.InvalidArgument, "task type cannot be empty")
	}

	//generate identity tracking token in memory
	taskID := uuid.New().String()

	// forward parameters to your routetask method (with explicit int64 type casting)
	err := s.trouter.RouteTask(ctx, taskID, req.TaskType, req.Payload, req.MaxRetries, int64(req.DelaySeconds))
	if err != nil {
		log.Printf("failed to route task: %v", err)
		return nil, status.Error(codes.Internal, "failed to route task")
	}

	//return response
	return &queuev1.EnqueueTaskResponse{
		TaskId:    taskID,
		Status:    "QUEUED",
		Timestamp: time.Now().Unix(),
	}, nil
}

// raw netowrk listener socket opening
func Start() {
	//Initialize your custom Redis connection pool pointer
	redisAddress := "localhost:6379"
	//wait for 3 seconds to boot up otherwise cancel
	// 3 seconds gaurd creating a boot context and checking if the task router is ready
	bootctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	//look for entire start to end then execute this
	defer cancel()

	taskRouter, err := NewTaskRouter(bootctx, redisAddress)
	if err != nil {
		log.Fatalf("failed to create task router: %v", err)
	}

	//Open the raw TCP socket listener channel on port 50051
	listener, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	//Initialize the core gRPC microservice server container
	grpcServer := grpc.NewServer()

	//Register our server implementation with the gRPC engine
	queuev1.RegisterQueueServiceServer(
		grpcServer,
		&server{
			trouter: taskRouter,
		})

	log.Println("gateway network online on port :50051")

	//Run the infinite network event execution loop
	// create an anonymous goroutine to serve the gRPC server
	go func() {
		err := grpcServer.Serve(listener)
		if err != nil && err != grpc.ErrServerStopped {
			log.Fatalf("critical error running gRPC server loop: %v", err)
		}
	}()
	//signal channel to listen for shutdown signals with buffer 1
	shutdownChan := make(chan os.Signal, 1)
	//if the process receives an interrupt or termination signal, send it to the shutdown channel
	signal.Notify(shutdownChan, os.Interrupt, syscall.SIGTERM)
	//block the main thrrad until shutdown signal is received
	sh := <-shutdownChan
	log.Printf("received shutdown signal: %v", sh)
	grpcServer.GracefulStop()
	log.Println("gateway network offline")

}
